### Fake News Classifier
######  Dataset: https://www.kaggle.com/c/fake-news/data?select=train.csv

In [3]:
!pip install pandas

The system cannot find the path specified.
You should consider upgrading via the 'C:\Users\AG20459\AppData\Local\Continuum\anaconda3\envs\tf2_2\python.exe -m pip install --upgrade pip' command.


In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('C:\\dataset\\fakenews\\train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [17]:
df = df.dropna()

In [18]:
# Independent Features
x = df.drop('label', axis=1)

In [19]:
# Dependent features
y = df['label']

In [20]:
x.shape

(18285, 4)

In [21]:
y.shape

(18285,)

In [22]:
import tensorflow as tf

In [23]:
tf.__version__

'2.3.1'

In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [25]:
# Vocab size
voc_size = 5000

##### Onehot Representation

In [27]:
messages = x.copy()
messages.reset_index(inplace=True)

In [33]:
messages['title']

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
18280    Rapper T.I.: Trump a ’Poster Child For White S...
18281    N.F.L. Playoffs: Schedule, Matchups and Odds -...
18282    Macy’s Is Said to Receive Takeover Approach by...
18283    NATO, Russia To Hold Parallel Exercises In Bal...
18284                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [29]:
!pip install nltk

Processing c:\users\ag20459\appdata\local\pip\cache\wheels\45\6c\46\a1865e7ba706b3817f5d1b2ff7ce8996aabdd0d03d47ba0266\nltk-3.5-py3-none-any.whl
  Using cached regex-2020.9.27-cp37-cp37m-win_amd64.whl (268 kB)
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
The system cannot find the path specified.
You should consider upgrading via the 'C:\Users\AG20459\AppData\Local\Continuum\anaconda3\envs\tf2_2\python.exe -m pip install --upgrade pip' command.


In [30]:
 import nltk
 import re
 from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\AG20459\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [40]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

1
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
14965
14966
14967
14968
14969
14970
14971
14972
14973
14974
14975
14976
14977
14978
14979
14980
14981
14982
14983
14984
14985
14986
14987
14988
14989
14990
14991
14992
14993
14994
14995
14996
14997
14998
14999
15000
15001
15002
15003
15004
15005
15006
15007
15008
15009
15010
15011
15012
15013
15014
15015
15016
15017
15018
15019
15020
15021
15022
15023
15024
15025
15026
15027
15028
15029
15030
15031
15032
15033
15034
15035
15036
15037
15038
15039
15040
15041
15042
15043
15044
15045
15046
15047
15048
15049
15050
15051
15052
15053
15054
15055
15056
15057
15058
15059
15060
15061
15062
15063
15064
15065
15066
15067
15068
15069
15070
15071
15072
15073
15074
15075
15076
15077
15078
15079
15080
15081
15082
15083
15084
15085
15086
15087
15088
15089
15090
15091
15092
15093
15094
15095
15096
15097
15098
15099
15100
15101
15102
15103
15104
15105
15106
15107
15108
15109
15110
15111
15112
15113
15114
15115
15116
15117
15

In [41]:
corpus

chut new york time',
 'stranahan steve bannon nail media fight trump breitbart',
 'texa elector expect massiv corrupt relat elector colleg vote',
 'guilti power nullif counteract govern tyranni',
 'trillion new debt day',
 'tori councillor say homeless peopl elimin',
 'review hillbilli elegi tough love analysi poor back trump new york time',
 'crimin chief',
 'govern lie movi',
 'trump brexit defeat global anyway',
 'face congress sport offici begin confront sexual abus new york time',
 'airbnb end fight new york citi fine new york time',
 'big pharma martin shkreli suspend twitter breitbart',
 'next big tech corridor seattl vancouv planner hope new york time',
 'evid robot win race american job new york time',
 'see africa road new york time',
 'happen hip hop hillari goe dead broke brace',
 'bill maher high trump state free speech new era new york time',
 'l p g tour donald trump complic new york time',
 'legend art cashin trump presid new world order gold brexit great depress see pa

In [42]:
# In onehot we need index based on vocab size
onehot_rep = [one_hot(words, voc_size) for words in corpus]
onehot_rep 

, 4028, 2972, 2768, 797, 1929, 125],
 [2465, 2812, 1980, 4163],
 [118, 4496, 1902, 2351, 4422, 3471, 2138, 1370],
 [2213, 3308, 4730, 2498, 4823, 1474, 2071, 4038, 1402, 4006],
 [4264, 1259, 3804, 4121, 406, 1935, 3542, 2388],
 [1020, 1521, 1020, 3141, 1942, 3387],
 [1823, 2443, 3302, 3868, 4809, 3549, 2884, 2401, 3131, 4038, 1402, 4006],
 [766, 1114, 1751, 2533, 2001, 2096, 1668, 204, 2354, 4038, 1402, 4006],
 [1153, 849, 1535, 257, 3665, 1515, 4113, 2996],
 [1878, 3562, 1751, 3060, 4543, 178, 1153, 4090, 4038, 1402, 4006],
 [1099, 721, 4799, 2280, 1652],
 [2858, 3469, 4983, 3244, 1860, 1277, 3949, 2108, 2464, 4038, 1402, 4006],
 [4695, 524, 4366, 3226, 4707, 2348, 4434, 584, 661],
 [1241, 2313, 1225, 4238, 1010, 3502, 2465],
 [2980, 209, 1295, 1403, 2465, 4869, 632, 2354],
 [3492, 4809, 3388, 471, 2107, 3492],
 [2465, 3004, 4875, 3970],
 [1562, 4930, 1850, 4434, 462, 4624, 3349, 3053, 2388, 3492],
 [3300, 128, 4869, 4751, 3733, 507, 2465, 4038, 1402, 4006],
 [1404, 3349, 1857, 1710, 

In [44]:
sent_length = 20
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0 ...  239 1810 1112]
 [   0    0    0 ... 3601 4026 3492]
 [   0    0    0 ... 2518  161  481]
 ...
 [   0    0    0 ... 4038 1402 4006]
 [   0    0    0 ... 4232 2148 1033]
 [   0    0    0 ... 3067 4067 4665]]


In [45]:
len(embedded_docs)

18285

In [46]:
## Creating Model
embedding_vec_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vec_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [47]:
len(embedded_docs),y.shape

(18285, (18285,))

In [49]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

X_final.shape, y_final.shape

((18285, 20), (18285,))

In [54]:
X_final

array([[   0,    0,    0, ...,  239, 1810, 1112],
       [   0,    0,    0, ..., 3601, 4026, 3492],
       [   0,    0,    0, ..., 2518,  161,  481],
       ...,
       [   0,    0,    0, ..., 4038, 1402, 4006],
       [   0,    0,    0, ..., 4232, 2148, 1033],
       [   0,    0,    0, ..., 3067, 4067, 4665]])

In [52]:
!pip install sklearn


Processing c:\users\ag20459\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e\sklearn-0.0-py2.py3-none-any.whl
  Using cached scikit_learn-0.23.2-cp37-cp37m-win_amd64.whl (6.8 MB)
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
The system cannot find the path specified.
You should consider upgrading via the 'C:\Users\AG20459\AppData\Local\Continuum\anaconda3\envs\tf2_2\python.exe -m pip install --upgrade pip' command.


In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [72]:
## Model Training
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 3s 16ms/step - loss: 0.3466 - accuracy: 0.8424 - val_loss: 0.2037 - val_accuracy: 0.9165
Epoch 2/10
192/192 [==============================] - 5s 24ms/step - loss: 0.1455 - accuracy: 0.9447 - val_loss: 0.1956 - val_accuracy: 0.9225
Epoch 3/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0978 - accuracy: 0.9641 - val_loss: 0.2425 - val_accuracy: 0.9216
Epoch 4/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0711 - accuracy: 0.9743 - val_loss: 0.2371 - val_accuracy: 0.9120
Epoch 5/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0525 - accuracy: 0.9821 - val_loss: 0.2710 - val_accuracy: 0.9175
Epoch 6/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0358 - accuracy: 0.9876 - val_loss: 0.3630 - val_accuracy: 0.9153
Epoch 7/10
192/192 [==============================] - 5s 26ms/step - loss: 0.0249 - accuracy: 0.9910 - val_loss: 0.3319 - val_accuracy: 0.9157

In [71]:
## Adding Dropout
from tensorflow.keras.layers import Dropout
# Creating model
embedding_vec_features = 40
model =  Sequential()
model.add(Embedding(voc_size, embedding_vec_features, input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [73]:
## Performance Metrics and Accuracy
y_pred = model.predict_classes(X_test)

In [74]:
from sklearn.metrics import confusion_matrix

In [75]:
confusion_matrix(y_test, y_pred)

array([[3124,  295],
       [ 244, 2372]], dtype=int64)

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9106876553438277