In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
X =  iris.data

In [8]:
# X

In [9]:
y = iris.target

In [10]:
# One hot encoding - categorical labelling
# class 0 ---> [1,0,0]
# class 1 ---> [0,1,0]
# class 2 ---> [0,0,1]

In [11]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
# y

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [17]:
# MinMax it divides all the value with the max value
from sklearn.preprocessing import MinMaxScaler

In [18]:
# np.array([5,10,15,20])/20

In [19]:
scaler_obj = MinMaxScaler()

In [20]:
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler_obj.transform(X_train)

In [22]:
scaled_X_test = scaler_obj.transform(X_test)

In [23]:
# scaled_X_train

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,input_dim=4,activation='softmax')) # [0.2, 0.3, 0.5]
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(scaled_X_train, y_train, epochs=200, verbose=2)

Epoch 1/200
 - 0s - loss: 0.5000 - accuracy: 0.6600
Epoch 2/200
 - 0s - loss: 0.4977 - accuracy: 0.6800
Epoch 3/200
 - 0s - loss: 0.4954 - accuracy: 0.6800
Epoch 4/200
 - 0s - loss: 0.4932 - accuracy: 0.6800
Epoch 5/200
 - 0s - loss: 0.4917 - accuracy: 0.7200
Epoch 6/200
 - 0s - loss: 0.4894 - accuracy: 0.7500
Epoch 7/200
 - 0s - loss: 0.4873 - accuracy: 0.7800
Epoch 8/200
 - 0s - loss: 0.4853 - accuracy: 0.7900
Epoch 9/200
 - 0s - loss: 0.4833 - accuracy: 0.7700
Epoch 10/200
 - 0s - loss: 0.4809 - accuracy: 0.7300
Epoch 11/200
 - 0s - loss: 0.4788 - accuracy: 0.7200
Epoch 12/200
 - 0s - loss: 0.4767 - accuracy: 0.7100
Epoch 13/200
 - 0s - loss: 0.4747 - accuracy: 0.7100
Epoch 14/200
 - 0s - loss: 0.4728 - accuracy: 0.7100
Epoch 15/200
 - 0s - loss: 0.4709 - accuracy: 0.7100
Epoch 16/200
 - 0s - loss: 0.4693 - accuracy: 0.7100
Epoch 17/200
 - 0s - loss: 0.4672 - accuracy: 0.7100
Epoch 18/200
 - 0s - loss: 0.4656 - accuracy: 0.7300
Epoch 19/200
 - 0s - loss: 0.4637 - accuracy: 0.7400
Ep

Epoch 155/200
 - 0s - loss: 0.2665 - accuracy: 0.9500
Epoch 156/200
 - 0s - loss: 0.2652 - accuracy: 0.9500
Epoch 157/200
 - 0s - loss: 0.2639 - accuracy: 0.9500
Epoch 158/200
 - 0s - loss: 0.2634 - accuracy: 0.9600
Epoch 159/200
 - 0s - loss: 0.2629 - accuracy: 0.9600
Epoch 160/200
 - 0s - loss: 0.2625 - accuracy: 0.9600
Epoch 161/200
 - 0s - loss: 0.2629 - accuracy: 0.9600
Epoch 162/200
 - 0s - loss: 0.2635 - accuracy: 0.9800
Epoch 163/200
 - 0s - loss: 0.2627 - accuracy: 0.9800
Epoch 164/200
 - 0s - loss: 0.2618 - accuracy: 0.9800
Epoch 165/200
 - 0s - loss: 0.2592 - accuracy: 0.9800
Epoch 166/200
 - 0s - loss: 0.2556 - accuracy: 0.9700
Epoch 167/200
 - 0s - loss: 0.2539 - accuracy: 0.9600
Epoch 168/200
 - 0s - loss: 0.2515 - accuracy: 0.9600
Epoch 169/200
 - 0s - loss: 0.2499 - accuracy: 0.9600
Epoch 170/200
 - 0s - loss: 0.2487 - accuracy: 0.9500
Epoch 171/200
 - 0s - loss: 0.2472 - accuracy: 0.9500
Epoch 172/200
 - 0s - loss: 0.2465 - accuracy: 0.9600
Epoch 173/200
 - 0s - loss: 

In [29]:
# How do we predict for unseen data

In [30]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [33]:
# model.predict(scaled_X_test)
# Classes are the index position
predictions = model.predict_classes(scaled_X_test)

In [34]:
# argmax gives the index value of the max value
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [36]:
# y_test

In [37]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [38]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [39]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

   micro avg       0.96      0.96      0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [40]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.96


In [41]:
model.save('myfirstmodel.h5')

In [42]:
from keras.models import load_model

In [43]:
new_model = load_model('myfirstmodel.h5')

In [44]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)